import Link from "next/link";
import { requirePermission } from "@/lib/session";
import { getCreatorByUserId } from "@/lib/creators";
import { prisma } from "@/lib/prisma";
import { createBundleAction } from "./actions";

export const metadata = { title: "สร้างชุดสื่อ" };
export default async function BundlesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const session = await requirePermission("product:create"); const creator = await getCreatorByUserId(session.user.id); if (!creator) return null;
  const [products, bundles, { error }] = await Promise.all([prisma.product.findMany({ where: { creatorId: creator.id, status: "PUBLISHED", visibility: "PUBLIC", deletedAt: null }, orderBy: { publishedAt: "desc" } }), prisma.bundle.findMany({ where: { creatorId: creator.id }, orderBy: { createdAt: "desc" } }), searchParams]);
  return <div className="max-w-3xl"><h1 className="font-headline text-2xl font-bold">สร้างชุดสื่อการสอน</h1><p className="text-sm text-text-muted mt-1 mb-7">รวมสื่อของคุณอย่างน้อย 2 ชิ้น เพื่อเสนอราคาพิเศษให้ผู้ซื้อ</p>{error && <p className="mb-4 bg-red-50 text-danger text-sm p-3 rounded-lg">เลือกสื่ออย่างน้อย 2 ชิ้น ตั้งชื่อ และกำหนดราคาให้ถูกต้อง</p>}<form action={createBundleAction} className="bg-white rounded-2xl border border-gray-100 p-6 space-y-5"><input required name="title" placeholder="เช่น ชุดใบงานคณิตศาสตร์ ป.3" className="w-full border rounded-lg px-3 py-2"/><textarea name="description" placeholder="อธิบายสิ่งที่ผู้ซื้อจะได้รับ" className="w-full border rounded-lg px-3 py-2 min-h-24"/><input required min="0" step="0.01" type="number" name="price" placeholder="ราคาชุด (บาท)" className="w-full border rounded-lg px-3 py-2"/><fieldset><legend className="font-medium text-sm mb-3">เลือกสื่อในชุด</legend>{products.length ? <div className="divide-y border rounded-lg">{products.map(product => <label key={product.id} className="flex gap-3 p-3 text-sm cursor-pointer"><input type="checkbox" name="productIds" value={product.id}/><span className="flex-1">{product.title}</span><span className="text-primary">฿{product.price.toNumber()}</span></label>)}</div> : <p className="text-sm text-text-muted">ต้องมีสื่อที่เผยแพร่แล้วอย่างน้อย 2 ชิ้น · <Link href="/dashboard/products/new" className="text-primary underline">เพิ่มสื่อใหม่</Link></p>}</fieldset><button disabled={products.length < 2} className="w-full bg-primary disabled:bg-gray-300 text-white font-medium py-3 rounded-xl">เผยแพร่ชุดสื่อ</button></form>{bundles.length > 0 && <section className="mt-8"><h2 className="font-headline font-bold">ชุดสื่อของฉัน</h2><div className="mt-3 space-y-2">{bundles.map(bundle => <Link key={bundle.id} href={`/bundles/${bundle.slug}`} className="block bg-white border rounded-xl p-4 text-sm hover:border-primary"><b>{bundle.title}</b><span className="float-right text-primary">฿{bundle.price.toNumber()}</span></Link>)}</div></section>}</div>;
}
